apiVersion: 1

datasources:
- name: MySQL
  type: mysql
  url: percona.bbdd.svc.cluster.local:3306
  user: grafana
  jsonData:
    database: synthetics
    maxOpenConns: 100
    maxIdleConns: 100
    maxIdleConnsAuto: true
    connMaxLifetime: 14400
  secureJsonData:
    password: ${GRAFANA_MYSQL_PASSWORD}
