{
 "title": "Mysql",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Conteo Total de Monitores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "synthetics",
     "rawSql": "SELECT COUNT(*) AS total_count\nFROM monitoring;\n"
    }
   ]
  },
  {
   "title": "step status",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "synthetics",
     "rawSql": "SELECT \n    COALESCE(step_status, 'null') AS step_status,\n    COUNT(*) AS count\nFROM monitoring\nGROUP BY step_status;\n"
    }
   ]
  },
  {
   "title": "Sondas",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "synthetics",
     "rawSql": "SELECT \n    monitor_name AS \"Nombre del Monitor\", \n    step_name AS \"Nombre del Paso\", \n    step_status AS \"Estado del Paso\"\nFROM \n    monitoring\n\n"
    }
   ]
  }
 ]
}