apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-conf
  namespace: grafana
type: Opaque
data:
  admin-password: U2VjcmV0UEBhc3N3b3Jk
  mysql-password: U2VjcmV0UEBhc3N3b3Jk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0
      containers:
      - name: grafana
        image: grafana-personalizado:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http-grafana
          protocol: TCP
        env:
        - name: GRAFANA_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-conf
              key: mysql-password
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-conf
              key: admin-password
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
          claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: http-grafana
    nodePort: 32000
  selector:
    app: grafana
  type: NodePort
